// test-smtp-send.js
const nodemailer = require("nodemailer");

async function testSMTP() {
  let transporter = nodemailer.createTransport({
    host: "localhost", // same as your SMTP server's host
    port: 25, // your SMTP port
    secure: false, // false for localhost or non-TLS test
    tls: { rejectUnauthorized: false }, // Allow self-signed certificates
  });

  let info = await transporter.sendMail({
    from: '"parminder singh" <parminder@kosh.com>',
    to: "parminder@rajdoot.wtf",
    subject: "Welcome to the Local SMTP Test Newsletter",
    replyTo: "no-reply@example.com",
    headers: {
      "X-Mailer": "Nodemailer Local Test",
      "List-Unsubscribe": "<mailto:unsubscribe@example.com>",
    },
    text: `Hi Parminder,

Thank you for trying your local SMTP server. This message demonstrates:
- Plain-text + rich HTML parts
- Headings, lists, and a call-to-action
- Attachments and an inline image

What’s inside:
1) Overview
2) Next steps
3) Contact & unsubscribe info

Overview
Your local server accepted a connection and this email was generated by a Node.js script using Nodemailer.

Next steps
- Click the button in the HTML version to visit a local link.
- Check that headers look correct.
- Verify the inline image and attachments appear.

Contact
Reply to this email or reach us at support@example.com.

Unsubscribe
If you didn’t expect this, you can ignore it on a test system or remove your address from the script.

— The Mail Test Bot`,
    html: `<!doctype html>
<html>
<body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;padding:20px;background:#0b1220;">
        <div style="max-width:840px;margin:0 auto;background:#081021;border:1px solid rgba(255,255,255,0.04);border-radius:8px;overflow:hidden;box-shadow:0 6px 18px rgba(2,6,23,0.6);">
                <div style="padding:20px;background:linear-gradient(90deg,#075985,#0ea5e9);color:#0b1220;display:flex;align-items:center;">
                        <img src="cid:logo@local" alt="Logo" width="32" height="32" style="vertical-align:middle;margin-right:10px;border-radius:4px;background:#081021;padding:4px;" />
                        <span style="font-size:18px;font-weight:600;color:#081021;">Local SMTP Test</span>
                </div>
                <div style="padding:24px;color:#e6edf3;">
                        <h1 style="margin:0 0 12px 0;font-size:20px;color:#ffffff;">Hello, Parminder 👋</h1>
                        <p style="margin:0 0 16px 0;line-height:1.6;color:#cbd5e1;">
                                This is a richer sample email sent through your locally running SMTP server. It includes text and HTML parts, an inline image, headers, and attachments.
                        </p>

                        <h2 style="margin:24px 0 8px 0;font-size:16px;color:#e6f6ff;">Highlights</h2>
                        <ul style="margin:0 0 16px 20px;color:#cbd5e1;">
                                <li>Clean responsive layout with inline styles</li>
                                <li>Call-to-action button</li>
                                <li>A small inline image (CID)</li>
                                <li>Attachments for reference</li>
                        </ul>

                        <table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;margin:16px 0;color:#cbd5e1;">
                                <tr>
                                        <td style="padding:8px;border:1px solid rgba(255,255,255,0.04);background:rgba(255,255,255,0.02);">Environment</td>
                                        <td style="padding:8px;border:1px solid rgba(255,255,255,0.04);">localhost (port 25)</td>
                                </tr>
                                <tr>
                                        <td style="padding:8px;border:1px solid rgba(255,255,255,0.04);background:rgba(255,255,255,0.02);">Transport</td>
                                        <td style="padding:8px;border:1px solid rgba(255,255,255,0.04);">Nodemailer</td>
                                </tr>
                        </table>

                        <p style="margin:0 0 16px 0;">
                                <a href="http://localhost" style="background:#06b6d4;color:#071025;text-decoration:none;padding:10px 16px;border-radius:6px;display:inline-block;font-weight:600;">
                                        Visit Localhost
                                </a>
                        </p>

                        <p style="margin:16px 0 0 0;font-size:12px;color:#94a3b8;">
                                If you did not expect this message, you can safely ignore it in a testing environment.
                        </p>
                </div>

                <div style="padding:16px;background:#071022;color:#7f8aa6;font-size:12px;text-align:center;border-top:1px solid rgba(255,255,255,0.02);">
                        © ${new Date().getFullYear()} Mail Test Bot • Unsubscribe: <a href="mailto:unsubscribe@example.com" style="color:#9bd6ee;text-decoration:underline;">unsubscribe@example.com</a>
                </div>
        </div>
</body>
</html>`,
    attachments: [
      {
        filename: "logo.png",
        content: Buffer.from(
          "iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAALElEQVQ4jWNgGAWjYBSMglEwCkZg1H8GQxGmYQ0wGgYB4YwEwz8G8TgAA8K4Kc1y1kq0AAAAASUVORK5CYII=",
          "base64"
        ),
        contentType: "image/png",
        cid: "logo@local",
      },
      {
        filename: "README.txt",
        content:
          "Nodemailer local SMTP test.\nThis file was attached to demonstrate attachments.\n",
        contentType: "text/plain",
      },
    ],
  });

  console.log("Message sent:", info.messageId);
}

testSMTP().catch(console.error);
